# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://digitaleducationsafety.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title      : Digital Education & Safety Foundation
email      : hello@digitaleducationsafety.org #this is also the email contact forms will go to
tagline    : "Empowering the under-served with a modern STEM education"
description: "Empowering the under-served with a modern STEM education"
author     : Digital Education & Safety Foundation
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

# Removing for now since we are trying Cloudflare Zaraz
#analytics:
  #google: G-KEP2448L3X #Google Analytics tracking code here

ads:
  google: AW-16943605271 #Google Ads code here

collections:
  programs:
    output: true
    path: /programs/:path/
  products:
  categories:
    output: true
  resources:
    output: true
    path: /resources/:path/
  definitions:
    output: true
    path: /definitions/:path/
    date: 2025-02-17
  opensource:
    output: true
    path: /open-source/:path/ 
  organizations:
    output: true
    path: /organizations/:path/
  marketplace:
    output: true
    path: /marketplace/:path/   
  services:
    output: true

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/xkgoddyo"

contact_form_action: "https://docs.google.com/forms/d/e/1FAIpQLSfVrEX0Fiy6xGPQ9xxJD0sFsygD8k7laf8GjrHDjcXNVhgcaA/formResponse"

turnstile_sitekey: "0x4AAAAAAADF-VDrlBmuOtjT"
turnstile_sitekey_mc: "0x4AAAAAACNF-Oav6RmaR0-r"
paypal_client_id: "AS6SHvzpq2yfxtT4bKPJxK_EyXUiYDdtzePeY3t7RLHjavm9vlyMCzybiULu6a_tl6GdbpHekuqy49sr" # Default sandbox ID
paypal_currency: "USD"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed


ein: "88-3764028"

feed:
  tags: true
  collections:
    - definitions

author:
  twitter: digitaledsafety
  name: digitaledsafety
  email: hello@digitaleducationsafety.org

twitter:
  username: digitaledsafety
  card: summary_large_image

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "definitions"
    values:
      layout: "definition"
      image: /assets/img/glossaries/mast.jpg
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "resources"
    values:
      layout: "resource"
      image: /assets/img/glossaries/mast.jpg      
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "organizations"
    values:
      layout: "organization"
      image: /assets/img/header-bg.jpg

